### ISSUE TITLE
Toolbar switch Will not minimize after maximized

### ISSUE THREAD

**Issue by sanelson2000** [paulveldema/ckeditor-plugins#2]
Using Toolbar switch on Maximize v.4.2.3 on CKEditor 4.2, after creating my own blank CKeditor_OnComplete function, the plugin works without throwing JavaScript errors, and it maximizes and switches to the maximized toolbar fine, but it will not minimize once it has been maximized.  The flow of events is this:
1. Create editor, works fine.  Editor is in normal mode. Toolbar is in small mode.
2. Click 'Toolbarswitch' button.  Editor goes into full screen mode, and toolbar switches to maximized toolbar.
3. Click 'Toolbarswitch' button. Editor stays in full screen mode, but toolbar to minimized toolbar.
4. Click 'Toolbarswitch' button. Screen flashes. Editor stays in full screen mode. Toolbar stays in minimized toolbar.

My config.js file looks like this:

``` javascript
CKEDITOR.editorConfig = function( config )
{

    config.extraPlugins = 'toolbarswitch';
    config.removePlugins = 'about,a11yhelp,dialogadvtab,bidi,templates,newpage,pagebreak,scayt,wsc,forms,div,flash,smiley,save,print,preview';
    config.toolbar =
        [
            { name: 'styles', items : [ 'Format' ] },
            { name: 'basicstyles', items : [ 'Bold','Italic','Strike'] },
            { name: 'links', items : [ 'Link', 'Unlink' ] },
            { name: 'paragraph', items : [ 'NumberedList','BulletedList','Blockquote','Outdent','Indent' ] },
            { name: 'tools', items : [ 'Toolbarswitch' ] }
        ];
    config.smallToolbar = config.toolbar;
    config.maximizedToolbar =
        [
            { name: 'clipboard', items : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ] },
            { name: 'editing', items : [ 'Find','Replace'] },
            { name: 'insert', items : [ 'Image','Table','HorizontalRule','SpecialChar' ] },
            { name: 'links', items : [ 'Link','Unlink' ] },
            '/',
            { name: 'styles', items : [ 'Styles','Format' ] },
            { name: 'basicstyles', items : [ 'Bold','Italic','Strike'] },
            { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote' ] },
            { name: 'tools', items : [ 'Toolbarswitch' ] }
        ];
}

```

**Comment by paulveldema** [comment]
[UPDATE]: I just realized sanelson == Scot Nelson :)

> Uncaught ReferenceError: CKeditor_OnComplete is not defined

Nog a bug:
The requirement of a dummy/empty CKeditor_OnComplete or your own code and why is clearly mentioned in the requirement list here:  http://ckeditor.com/addon/toolbarswitch

> My config.js file looks like this:

Your maximizedToolbar uses the maximize button. All toolbars used in the ckeditor instance must use the Toolbarswitch button.
I will adjust the explanation on the plug-in page to be more explicit about that.

Let me know if that fixes your problem.

If it still does not work you probably have the same problem as:
https://github.com/paulveldema/ckeditor-plugins/issues/2
I will examine that bug report next week.

With Regards,
Paul
Op dinsdag, 17 september 2013 16:46 schreef Scott Nelson notifications@github.com:

**Comment by paulveldema** [comment]
I do have a question though. Are there no java script errors on step 3?

**Comment by sanelson2000** [comment]
Sorry, I tried to edit out the initial issue and replace it with the second one. I guess that wasn't a good idea.

No, there are no javascript errors being thrown once I added the CKeditor_OnComplete function and changed the 'Maximize' button to 'Toolbarswitch'.  It is just not minimizing properly.  The screen flashes for a second like it is trying to work, but the editor stays in full screen mode with a minimized toolbar.

Thanks.

**Comment by paulveldema** [comment]
I tried your config and it did not even show a toolbar (not maximized or normal).

The 'config.toolbar' and 'config.maximizedToolbar' are ok (works with my own config).
I think the lines with 'config.extraPlugins' and 'config.removePlugins' are the problem.

Personally I use a single 'config.plugins = ' line and that works for me. You can simply copy it from the generated config.js and one by one remove what you do not want (test with a cleared cache at every removal).

Also there is a new version of the plug-in that works just a little better.
To get it you need to get it from github at the moment as it is still pending on the plug-in page.

Hope this helps, let me know.

**Comment by sanelson2000** [comment]
Hi Paul,

I've tried the latest version, and I've tried changing the config.plugins to a single line option, and I'm still having the same issue. I've uploaded a very simple example showing the issue here:
http://bit.ly/16S5mUU

My config.js file is here: 
http://bit.ly/19AtM5k

Any thoughts?

Thanks,
Scott

**Comment by Voetganger** [comment]
Hi Paul and Scott,

I ran into the exact same problem this morning and haven't been able to solve it. Searching on the internet for a solution lead me to this recent thread. 

Is there any news or even a solution yet?

My code is like Scott's code.

Thanks a lot in advance.

Frank

**Comment by paulveldema** [comment]
@sanelson2000 thanks for the example. I am now able to reproduce the problem.
I have been busy with other work and will be busy with that for another week, maybe two.
After that I will take a closer look at this.

**Comment by Voetganger** [comment]
Solution (I believe it's actually not a bug in the plugin):

## custom-config:

CKEDITOR.editorConfig = function( config ) {
    config.toolbar_minToolbar =
    [
        { name: 'mode', items : [ 'Toolbarswitch' ] },
        { name: 'basicstyles', items : [ 'Bold','Italic','Underline'] },
        { name: 'tools', items : [ 'ShowBlocks','Source' ] }
    ];
    config.toolbar_maxToolbar =
    [
        { name: 'mode', items : [ 'Toolbarswitch' ] },
        { name: 'basicstyles', items : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
        { name: 'tools', items : [ 'ShowBlocks','Source' ] }
    ];
    config.toolbar = 'minToolbar';
    config.extraPlugins = 'toolbarswitch';
}

## page:

$(window).load(function() { 
    CKEDITOR.replace('ckeditor', {
        smallToolbar: 'minToolbar',
        maximizedToolbar: 'maxToolbar',
        language: 'cs'
    });
});

function CKeditor_OnComplete(ckEditorInstance) { }

Hope this helps someone...
Cheers!

**Comment by sanelson2000** [comment]
Thanks @Voetganger.

That worked for me.  So, the issue is that you can't just set config.smallToolbar and config.maximizedToolbar directly to toolbar configurations, but you need to create named toolbar configurations first and just set them to the name.  I was able to get this all working through config.js so that I only need to call CKEDITOR.replace with no extra parameters by adding the following to my config.js file.

``` javascript
    config.toolbar_minToolbar = [...]; // Custom minimized toolbar config
    config.toolbar_maxToolbar = [...]; // Custom maximized toolbar config
    config.toolbar = 'minToolbar';
    config.smallToolbar = 'minToolbar';
    config.maximizedToolbar = 'maxToolbar';
```

Like you said, I'm not sure if it's actually a bug in the plugin, but perhaps the documentation could be a bit more clear on how to configure it.  Yes, I know it does say to set it to 'yoursmalltoolbarname' and 'yourbigtoolbarname', but this is my first time using CKEditor, and those instructions didn't really make sense to me.  I just assumed that the name was a reference to an old way of configuring the toolbars via strings, and the array/hash method was the new way...

Anyway, I suppose this can be closed if it's not an actual bug.  I would make the following recommendations, though, to make it more newb-friendly.

1) Better examples, including the contents of the custom_ckeditor_config.js file, and also an example updating config.js directly with all of the settings so that CKEDITOR.replace can be used without passing any extra parameters (assuming you want to use the same config throughout your site).
2) Include an empty CKeditor_OnComplete function with the plugin, with instructions to override it if necessary.  Perhaps this is not possible due to the way CKEditor loads the JS files???

Thanks again, @paulveldema for your work on this plugin.  It seems to be working well, now that I've figured out how it works.
