### ISSUE TITLE
Changes lost when minimizing if smallToolbar does not contain button used in maximizedToolbar

### ISSUE THREAD

**Issue by sanelson2000** [paulveldema/ckeditor-plugins#3]
OK, I found one more issue with the ToolbarSwitch plugin (and I think this one is for real ;-) ).  It seems that any plugins containing features (extra HTML) used in the maximizedToolbar configuration must also be present in the smallToolbar configuration, otherwise, when you minimize again, any changes that you made using plugins not in the smallToolbar are lost.

For example, if my maximizedToolbar contains 'horizontalrule' but my smallToolbar doesn't, when I go into the maximized window and add a HR, it is stripped from my editor when I minimized again.

Here is an example page where you can test this out.
http://bit.ly/HdGKcL
And the config.js file:
http://bit.ly/1bPqhph

Go to the page, type something in the editor area, then switch toolbars.
While in maximized mode, add a horizontal rule, or a table, or try changing styles.  When you minimize again, any HTML content that doesn't align with the smallToolbar config is stripped out of the editor.  Even if you switch back to the maximized version, it appears to be gone forever.

**Comment by paulveldema** [comment]
Not a bug. This filtering is a 'feature' of the new ckeditor versions (starting at 4.1 I think): advanced content filtering.

You can turn that off with:
config.allowedContent = true;

Paul
